name: riverpod_app
description: "A project to understand Riverpod."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
